variables:
- group: demo-vm-deploy

trigger:
- master
- andrei
- stefan

stages:
- stage: Build
  displayName: Build and Validate
  jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: validate lab template
      inputs:
        azureSubscription: $(testAzureConnection)
        resourceGroupName: $(testResourceGroupName)
        templateLocation: 'Linked artifact'
        csmFile: $(Build.SourcesDirectory)/lab/azuredeploy.json
        csmParametersFile: $(Build.SourcesDirectory)/lab/azuredeploy.parameters.json
        deploymentMode: 'Validation'

    - task: AzureResourceGroupDeployment@2
      displayName: validate vm template
      inputs:
        azureSubscription: $(testAzureConnection)
        resourceGroupName: $(testResourceGroupName)
        templateLocation: 'Linked artifact'
        csmFile: $(Build.SourcesDirectory)/vm/azuredeploy.json
        csmParametersFile: $(Build.SourcesDirectory)/vm/azuredeploy.parameters.json
        deploymentMode: 'Validation'

    - task: AzureResourceGroupDeployment@2
      displayName: validate env template
      inputs:
        azureSubscription: $(testAzureConnection)
        resourceGroupName: $(testResourceGroupName)
        templateLocation: 'Linked artifact'
        csmFile: $(Build.SourcesDirectory)/Environments/PresalesDemo/azuredeploy.json
        csmParametersFile: $(Build.SourcesDirectory)/Environments/PresalesDemo/azuredeploy.parameters.json
        deploymentMode: 'Validation'

- stage: DeployUAT
  displayName: Deploy to UAT
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: deployUAT
      environment: uat
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureResourceGroupDeployment@2
              displayName: deploy lab to test
              inputs:
                azureSubscription: $(testAzureConnection)
                resourceGroupName: $(testResourceGroupName)
                templateLocation: 'Linked artifact'
                csmFile: $(Build.SourcesDirectory)/lab/azuredeploy.json
                csmParametersFile: $(Build.SourcesDirectory)/lab/azuredeploy.parameters.json
                deploymentMode: 'Incremental'
                overrideParameters: -tenantId $(tenantId) -objectId $(objectId) -gitToken $(githubToken) -projectName "dsftest"

- stage: DeployProd
  displayName: Deploy to Prod
  dependsOn: DeployUAT
  condition: succeeded()
  jobs:
    - deployment: deployProd
      environment: prod
      pool:
        vmImage: 'ubuntu-latest'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: AzureResourceGroupDeployment@2
              displayName: deploy lab to test
              inputs:
                azureSubscription: $(prodAzureConnection)
                resourceGroupName: $(prodResourceGroupName)
                templateLocation: 'Linked artifact'
                csmFile: $(Build.SourcesDirectory)/lab/azuredeploy.json
                csmParametersFile: $(Build.SourcesDirectory)/lab/azuredeploy.parameters.json
                deploymentMode: 'Incremental'
                overrideParameters: -tenantId $(tenantId) -objectId $(objectId) -gitToken $(githubToken) -projectName "dsf"
              
