variables:
- group: demo-vm-deploy

trigger:
- master
- andrei
- stefan

stages:
- stage: Build
  displayName: Build and Test
  jobs:
  - job: Validate
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: validate lab template
      inputs:
        azureSubscription: $(testAzureConnection)
        resourceGroupName: $(testResourceGroupName)
        templateLocation: 'Linked artifact' # Options: linked Artifact, uRL Of The File
        csmFile: $(Build.SourcesDirectory)/lab/azuredeploy.json # Required when  TemplateLocation == Linked Artifact
        csmParametersFile: $(Build.SourcesDirectory)/lab/azuredeploy.parameters.json # Optional
        deploymentMode: 'Validation' # Options: Incremental, Complete, Validation

    - task: AzureResourceGroupDeployment@2
      displayName: validate vm template
      inputs:
        azureSubscription: $(testAzureConnection)
        resourceGroupName: $(testResourceGroupName)
        templateLocation: 'Linked artifact' # Options: linked Artifact, uRL Of The File
        csmFile: $(Build.SourcesDirectory)/vm/azuredeploy.json # Required when  TemplateLocation == Linked Artifact
        csmParametersFile: $(Build.SourcesDirectory)/vm/azuredeploy.parameters.json # Optional
        deploymentMode: 'Validation' # Options: Incremental, Complete, Validation

    - task: AzureResourceGroupDeployment@2
      displayName: validate env template
      inputs:
        azureSubscription: $(testAzureConnection)
        resourceGroupName: $(testResourceGroupName)
        templateLocation: 'Linked artifact' # Options: linked Artifact, uRL Of The File
        csmFile: $(Build.SourcesDirectory)/Environment/PresalesDemo/azuredeploy.json # Required when  TemplateLocation == Linked Artifact
        csmParametersFile: $(Build.SourcesDirectory)/Environment/PresalesDemo/azuredeploy.parameters.json # Optional
        deploymentMode: 'Validation' # Options: Incremental, Complete, Validation

  - job: DeployTest
    dependsOn: Validate
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: deploy lab to test
      inputs:
        azureSubscription: $(testAzureConnection)
        resourceGroupName: $(testResourceGroupName)
        templateLocation: 'Linked artifact' # Options: linked Artifact, uRL Of The File
        csmFile: $(Build.SourcesDirectory)/lab/azuredeploy.json # Required when  TemplateLocation == Linked Artifact
        csmParametersFile: $(Build.SourcesDirectory)/lab/azuredeploy.parameters.json # Optional
        deploymentMode: 'Incremental' # Options: Incremental, Complete, Validation
        overrideParameters: -tenantId $(tenantId) -objectId $(objectId) -gitToken $(githubToken) -projectName "dsftest"



#    - task: AzureResourceGroupDeployment@2
#      displayName: validate vm template
#      inputs:
#        azureSubscription: $(testAzureConnection)
#        resourceGroupName: $(testResourceGroupName)
#        templateLocation: 'Linked artifact' # Options: linked Artifact, uRL Of The File
#        csmFile: $(Build.SourcesDirectory)/vm/azuredeploy.json # Required when  TemplateLocation == Linked Artifact
#        csmParametersFile: $(Build.SourcesDirectory)/vm/azuredeploy.parameters.json # Optional
#        deploymentMode: 'Validation' # Options: Incremental, Complete, Validation
#
#    - task: AzureResourceGroupDeployment@2
#      displayName: validate env template
#      inputs:
#        azureSubscription: $(testAzureConnection)
#        resourceGroupName: $(testResourceGroupName)
#        templateLocation: 'Linked artifact' # Options: linked Artifact, uRL Of The File
#        csmFile: $(Build.SourcesDirectory)/env/PresalesDemo/azuredeploy.json # Required when  TemplateLocation == Linked Artifact
#        csmParametersFile: $(Build.SourcesDirectory)/env/PresalesDemo/azuredeploy.parameters.json # Optional
#        deploymentMode: 'Validation' # Options: Incremental, Complete, Validation
    